version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    network_mode: host  # Traefik écoute directement sur les ports de l'hôte (80/443)
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.email=th.fargeon@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
      - "./traefik.yml:/traefik.yml"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.tfargeon.fr`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=thierry:$apr1$kRe0L.pd$vT4tl.JE1EXQNLcAozunf0"  # C'est le bon Hash a conserver`

  apache:
    image: httpd:alpine
    container_name: apache
    network_mode: host  # Apache écoute sur le port 8081 de l'hôte
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apache.rule=Host(`tfargeon.fr`)"
      - "traefik.http.routers.apache.entrypoints=websecure"
      - "traefik.http.routers.apache.tls.certresolver=myresolver"
      - "traefik.http.services.apache.loadbalancer.server.port=8081"
    volumes:
      - "/var/www/tfargeon.fr:/usr/local/apache2/htdocs"
